package clientapp

import "net/http"

func (s *httpAPIServer) registerHTTPRouteAdmin(mux *http.ServeMux, prefix string) {
	mux.HandleFunc(prefix+"/v1/admin/biz_workspaces", s.withAuth(s.handleAdminWorkspaces))
	mux.HandleFunc(prefix+"/v1/admin/downloads/resume", s.withAuth(s.handleAdminResumeDownload))
	mux.HandleFunc(prefix+"/v1/admin/fs-http/strategy-debug-log", s.withAuth(s.handleAdminStrategyDebugLog))
	mux.HandleFunc(prefix+"/v1/admin/live/streams", s.withAuth(s.handleAdminLiveStreams))
	mux.HandleFunc(prefix+"/v1/admin/live/streams/detail", s.withAuth(s.handleAdminLiveStreamDetail))
	mux.HandleFunc(prefix+"/v1/admin/live/storage/summary", s.withAuth(s.handleAdminLiveStorageSummary))
	mux.HandleFunc(prefix+"/v1/admin/static/tree", s.withAuth(s.handleAdminStaticTree))
	mux.HandleFunc(prefix+"/v1/admin/static/mkdir", s.withAuth(s.handleAdminStaticMkdir))
	mux.HandleFunc(prefix+"/v1/admin/static/upload", s.withAuth(s.handleAdminStaticUpload))
	mux.HandleFunc(prefix+"/v1/admin/workspace/register-downloaded-file", s.withAuth(s.handleAdminRegisterDownloadedFile))
	mux.HandleFunc(prefix+"/v1/admin/static/move", s.withAuth(s.handleAdminStaticMove))
	mux.HandleFunc(prefix+"/v1/admin/static/entry", s.withAuth(s.handleAdminStaticEntry))
	mux.HandleFunc(prefix+"/v1/admin/static/price/set", s.withAuth(s.handleAdminStaticPriceSet))
	mux.HandleFunc(prefix+"/v1/admin/static/price", s.withAuth(s.handleAdminStaticPriceGet))
	mux.HandleFunc(prefix+"/v1/admin/routes/indexes", s.withAuth(s.handleAdminRouteIndexes))
	// 费用池审计历史查询入口（非主入口，仅保留原始事实查询能力）
	// 主排障入口请使用 /v1/admin/feepool/audit/gateway-timeline 和 command-timeline
	mux.HandleFunc(prefix+"/v1/admin/feepool/commands", s.withAuth(s.handleAdminFeePoolCommands))
	mux.HandleFunc(prefix+"/v1/admin/feepool/commands/detail", s.withAuth(s.handleAdminFeePoolCommandDetail))
	mux.HandleFunc(prefix+"/v1/admin/feepool/events", s.withAuth(s.handleAdminFeePoolEvents))
	mux.HandleFunc(prefix+"/v1/admin/feepool/events/detail", s.withAuth(s.handleAdminFeePoolEventDetail))
	mux.HandleFunc(prefix+"/v1/admin/feepool/states", s.withAuth(s.handleAdminFeePoolStates))
	mux.HandleFunc(prefix+"/v1/admin/feepool/states/detail", s.withAuth(s.handleAdminFeePoolStateDetail))
	mux.HandleFunc(prefix+"/v1/admin/feepool/observed-states", s.withAuth(s.handleAdminFeePoolObservedStates))
	mux.HandleFunc(prefix+"/v1/admin/feepool/observed-states/detail", s.withAuth(s.handleAdminFeePoolObservedStateDetail))
	mux.HandleFunc(prefix+"/v1/admin/feepool/effects", s.withAuth(s.handleAdminFeePoolEffects))
	mux.HandleFunc(prefix+"/v1/admin/feepool/effects/detail", s.withAuth(s.handleAdminFeePoolEffectDetail))
	// 费用池审计主入口（时间线统一视角）
	mux.HandleFunc(prefix+"/v1/admin/feepool/audit/gateway-timeline", s.withAuth(s.handleAdminFeePoolGatewayAuditTimeline))
	mux.HandleFunc(prefix+"/v1/admin/feepool/audit/command-timeline", s.withAuth(s.handleAdminFeePoolCommandAuditTimeline))
	mux.HandleFunc(prefix+"/v1/admin/client-kernel/commands", s.withAuth(s.handleAdminClientKernelCommands))
	mux.HandleFunc(prefix+"/v1/admin/client-kernel/commands/detail", s.withAuth(s.handleAdminClientKernelCommandDetail))
	mux.HandleFunc(prefix+"/v1/admin/orchestrator/logs", s.withAuth(s.handleAdminOrchestratorLogs))
	mux.HandleFunc(prefix+"/v1/admin/orchestrator/logs/detail", s.withAuth(s.handleAdminOrchestratorLogDetail))
	mux.HandleFunc(prefix+"/v1/admin/scheduler/tasks", s.withAuth(s.handleAdminSchedulerTasks))
	mux.HandleFunc(prefix+"/v1/admin/scheduler/runs", s.withAuth(s.handleAdminSchedulerRuns))
	mux.HandleFunc(prefix+"/v1/admin/chain/tip/status", s.withAuth(s.handleAdminChainTipStatus))
	mux.HandleFunc(prefix+"/v1/admin/chain/tip/logs", s.withAuth(s.handleAdminChainTipLogs))
	mux.HandleFunc(prefix+"/v1/admin/chain/utxo/status", s.withAuth(s.handleAdminChainUTXOStatus))
	mux.HandleFunc(prefix+"/v1/admin/chain/utxo/logs", s.withAuth(s.handleAdminChainUTXOLogs))
	mux.HandleFunc(prefix+"/v1/admin/wallet/utxos", s.withAuth(s.handleAdminWalletUTXOs))
	mux.HandleFunc(prefix+"/v1/admin/wallet/utxos/detail", s.withAuth(s.handleAdminWalletUTXODetail))
	mux.HandleFunc(prefix+"/v1/admin/verification/summary", s.withAuth(s.handleAdminVerificationSummary))
	mux.HandleFunc(prefix+"/v1/admin/verification/failed", s.withAuth(s.handleAdminVerificationFailed))
	mux.HandleFunc(prefix+"/v1/admin/verification/items", s.withAuth(s.handleAdminVerificationItems))
	mux.HandleFunc(prefix+"/v1/admin/verification/reconcile", s.withAuth(s.handleAdminVerificationReconcile))
	mux.HandleFunc(prefix+"/v1/admin/verification/reset", s.withAuth(s.handleAdminVerificationReset))
	mux.HandleFunc(prefix+"/v1/admin/verification/batch-retry", s.withAuth(s.handleAdminVerificationBatchRetry))
	mux.HandleFunc(prefix+"/v1/admin/finance/businesses", s.withAuth(s.handleAdminFinanceBusinesses))
	mux.HandleFunc(prefix+"/v1/admin/finance/businesses/detail", s.withAuth(s.handleAdminFinanceBusinessDetail))
	mux.HandleFunc(prefix+"/v1/admin/finance/process-events", s.withAuth(s.handleAdminFinanceProcessEvents))
	mux.HandleFunc(prefix+"/v1/admin/finance/process-events/detail", s.withAuth(s.handleAdminFinanceProcessEventDetail))
}
